version: '3'
services:
  mysql-container:
    image: mysql:8.0.30
    container_name: mysql-container2
    ports:
      - "3337:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mobileshopdb4
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    networks:
      - my-network2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mobileshop:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./resources/static/images:/app/res/static/images
    container_name: mobileshop2
    ports:
      - "8082:8083"
    networks:
      - my-network2

networks:
  my-network2:
    external: true