
FROM openjdk:8-jdk-alpine

WORKDIR /app

COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

COPY src/main/resources/static/images /app/res/static/images

RUN echo "spring.datasource.url=jdbc:mysql://mysql-container:3306/mobileshopdb4" > application.properties

CMD ["java", "-jar", "app.jar"]
